### ISSUE TITLE
为什么多了一层目录

### ISSUE THREAD

**Issue by zhoufanglu** [shanyuhai123/vuepress-plugin-auto-sidebar#10]
## 目录结构
![image](https://user-images.githubusercontent.com/24451091/83018358-be170500-a057-11ea-9434-763b74588e5d.png)
## 代码
```js
 plugins: {
    "vuepress-plugin-auto-sidebar": {
      nav: true
    }
  },
```
## 效果
![image](https://user-images.githubusercontent.com/24451091/83018432-dedf5a80-a057-11ea-8402-c01dd9519f07.png)

有`demo`吗  最好有demo参考。

**Comment by shanyuhai123** [comment]
这个没有多一层，md 文件不设置 title 就是这样，我有贴[更详细的文档](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/questions.html#_2-%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA-404%E3%80%82)啊，不显眼么。

**Comment by zhoufanglu** [comment]
> 这个没有多一层，md 文件不设置 title 就是这样，我有贴[更详细的文档](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/questions.html#_2-%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA-404%E3%80%82)啊，不显眼么。

好的，谢谢，是否可以实现点击标题 收缩展开？

**Comment by shanyuhai123** [comment]
不太理解你的意思，但这个本身就是点击标题会收缩展开的。
如果你是要多个分组时折叠可以看[这个参数](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/markdown-file-config.html#%E5%A4%9A%E4%B8%AA%E5%88%86%E7%BB%84)。

**Comment by zhoufanglu** [comment]
类似这种
![image](https://user-images.githubusercontent.com/24451091/83254312-35c46b80-a1e1-11ea-8787-c60db0c6bc66.png)
点击标题后收缩功能
![image](https://user-images.githubusercontent.com/24451091/83254382-44ab1e00-a1e1-11ea-82e3-87d402bdac98.png)

**Comment by shanyuhai123** [comment]
可以看下 [collapsable（折叠）](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/plugin-options.html#collapsable%EF%BC%88%E6%8A%98%E5%8F%A0%EF%BC%89) 这个配置项，[示例](https://docs.shanyuhai.top/frontend/javascript/)。

**Comment by zhoufanglu** [comment]
> 可以看下 [collapsable（折叠）](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/plugin-options.html#collapsable%EF%BC%88%E6%8A%98%E5%8F%A0%EF%BC%89) 这个配置项，[示例](https://docs.shanyuhai.top/frontend/javascript/)。

谢谢大佬 的回复，学到了，star一下
