### ISSUE TITLE
侧边栏多个一级菜单显示无效额？

### ISSUE THREAD

**Issue by LuBangTao** [shanyuhai123/vuepress-plugin-auto-sidebar#11]
我想要的效果如下
![4HBA0`WRX$E I@F`4CNV(RM](https://user-images.githubusercontent.com/22848900/84575428-76c29f80-addf-11ea-80ce-0f6d954ef29b.png)

但是我是通过设置 2级标题 实现的，一级标题加上没有用诶。。。
![image](https://user-images.githubusercontent.com/22848900/84575469-b6898700-addf-11ea-8840-d0d27a85563d.png)

想看你的源码改。。。结果原谅我、、、我没看不懂、、、

按习惯。。应该是一级标题 （一个#号）的才是正常的吧。。。不晓得为啥加不上去哦

有问题的示例：
文档：
![image](https://user-images.githubusercontent.com/22848900/84575576-a1612800-ade0-11ea-99e2-bf7a85741cb0.png)

效果：

![image](https://user-images.githubusercontent.com/22848900/84575608-dff6e280-ade0-11ea-8e94-96ce10dac0ba.png)

快来拯救下小老弟我把。。。

**Comment by shanyuhai123** [comment]
你在开头写了 `title` 这个等价于一级标题，而且优先级更高。
至于你想要多个一级标题，这个不符合文章规范，建议拆分成多个文章或使用二级标题。

**Comment by shanyuhai123** [comment]
如果你想改一级标题的优先级高于 `title` 或让其返回多个一级标题，那你应该去修改 `vuepress core` 部分的代码；如果你想展示所有的一级标题或其他的，那你应该去修改 `vuepress default` 主题部分的代码。
我这个插件只是接管默认主题下 `themeConfig` 的 `sidebar` 配置。

**Comment by LuBangTao** [comment]
哦哦，那我就不用一级标题了。，后面有空看看vuepress的东西
