### ISSUE TITLE
左侧菜单栏能否支持通过多级目录生成分组？

### ISSUE THREAD

**Issue by Yookoo** [shanyuhai123/vuepress-plugin-auto-sidebar#13]
```
---
autoGroup-1: 分组名称
# autoGroup+10: 分组名称
---
```
通过在文件中添加分组标签虽然也可以达到分组的效果，但是太多文件被放在同一个文件夹下，查找起来很麻烦，能否通过，将文件在不同的文件夹下，通过文件夹的名称作为组名，自动生成分组的效果。
目前的情况是，如果guide下还有文件夹就不能作为左侧菜单显示，例如：
```
-guide
- +--linux
       +-- linux.md
```
这样linux就无法被生成左侧的菜单。

**Comment by shanyuhai123** [comment]
如果以增加子文件夹来划分那就产生了新的问题：不同的目录在多少深度（几层子文件夹）时才划分为分组，配置起来感觉也并不直观。

这一块如果很多可以考虑下 [官网 nav](https://v1.vuepress.vuejs.org/zh/theme/default-theme-config.html#%E5%AF%BC%E8%88%AA%E6%A0%8F%E9%93%BE%E6%8E%A5) 的分组功能。

**Comment by Yookoo** [comment]
好的，我看一下，谢谢解答。
