### ISSUE TITLE
精确排序提示错误

### ISSUE THREAD

**Issue by kecrily** [shanyuhai123/vuepress-plugin-auto-sidebar#16]
我通过 `autoPrev` 和 `autoNext` 进行了精确排序，在进行 `yarn dev` 时，出现了如下提示。
![图片](https://user-images.githubusercontent.com/45708948/97584684-3e8cc800-1a33-11eb-85cc-338c27e5ccc8.png)
但实际上 `README.md`、`install.md`、`config.md` 均存在于同一目录 `guide` 下
![图片](https://user-images.githubusercontent.com/45708948/97585233-df7b8300-1a33-11eb-97ac-9426c8be6a67.png)
![图片](https://user-images.githubusercontent.com/45708948/97584757-5401f200-1a33-11eb-84ec-a951da87dcd2.png)
![图片](https://user-images.githubusercontent.com/45708948/97584775-59f7d300-1a33-11eb-918c-1db7ce0303e5.png)
![图片](https://user-images.githubusercontent.com/45708948/97584799-60864a80-1a33-11eb-815d-0603a21ac173.png)

**Comment by shanyuhai123** [comment]
你不能让这三个文件都进行精准排序，你至少有一个为基石（没有指向），其余的再排序在其前后。

**Comment by kecrily** [comment]
> 你不能让这三个文件都进行精准排序，你至少有一个为基石（没有指向），其余的再排序在其前后。

所以我只需要移除 `README.md` 的指向就好了吗？

**Comment by shanyuhai123** [comment]
是的。

**Comment by kecrily** [comment]
> 
> 
> 是的。

在我删除其他指向，仅保留
![图片](https://user-images.githubusercontent.com/45708948/97590397-84e52580-1a39-11eb-9159-fa034daa3cbf.png)
的指向，却仍然提示指向不存在的 prev 或 next

**Comment by shanyuhai123** [comment]
> 在我删除其他指向，仅保留
> ![图片](https://user-images.githubusercontent.com/45708948/97590397-84e52580-1a39-11eb-9159-fa034daa3cbf.png)
> 的指向，却仍然提示指向不存在的 prev 或 next

我按照你说的复现没有问题：
![image](https://user-images.githubusercontent.com/27122409/97592127-494b5b00-1a3b-11eb-9e2c-5244637b82d3.png)
![image](https://user-images.githubusercontent.com/27122409/97592174-536d5980-1a3b-11eb-87b6-c26a3f45e296.png)

**Comment by kecrily** [comment]
> 
> 
> > 在我删除其他指向，仅保留
> > ![图片](https://user-images.githubusercontent.com/45708948/97590397-84e52580-1a39-11eb-9159-fa034daa3cbf.png)
> > 的指向，却仍然提示指向不存在的 prev 或 next
> 
> 我按照你说的复现没有问题：
> ![image](https://user-images.githubusercontent.com/27122409/97592127-494b5b00-1a3b-11eb-9e2c-5244637b82d3.png)
> ![image](https://user-images.githubusercontent.com/27122409/97592174-536d5980-1a3b-11eb-87b6-c26a3f45e296.png)

我解决了，刚刚在 `install` 中多设置了一个 `autoPrev: config`。感谢
