### ISSUE TITLE
某个分组/文件夹/路由 不想显式侧边栏，如何设置

### ISSUE THREAD

**Issue by JasonGrass** [shanyuhai123/vuepress-plugin-auto-sidebar#19]
---
title: 关于
sidebar: false
---

sidebar: false 似乎无效

**Comment by shanyuhai123** [comment]
目前是缺乏这个功能的，不过你可以利用 `autoPrev` 来指向一个错误的路径来 hack 的方式实现。

![image](https://user-images.githubusercontent.com/27122409/110961851-36527b00-838b-11eb-8e38-a45432c114a0.png)

我应该会在下周末前发新的一版，并实现该功能。

**Comment by JasonGrass** [comment]
哈哈哈，`autoPrev ` 这个有效，期待新版本，[星星眼] 。

**Comment by shanyuhai123** [comment]
已经增加了该功能，目前有两种方式：
1. Markdown 文件内（隐藏单个）
```yaml
---
autoIgnore: true
---
```
2. 配置文件（隐藏多个）
```js
module.exports = {
  plugins: {
    "vuepress-plugin-auto-sidebar": {
      ignore: [
        // 例如忽略 `/menu3/menu3-3/` 目录下以 `ignore-` 开头的文件
        {
          menu: "/menu3/menu3-3/",
          regex: "ignore-*"
        }
      ]
    }
  }
}
```

**Comment by JasonGrass** [comment]
在 2.1.0 版本 测试成功，超级棒~
