### ISSUE TITLE
博主你好，请问使用插件之后生成的侧边栏为什么带.html扩展名？

### ISSUE THREAD

**Issue by supuwoerc** [shanyuhai123/vuepress-plugin-auto-sidebar#2]
RT，请问使用插件之后生成的侧边栏为什么带.html扩展名？我的文档目录是VuePressBlog\docs\toy文件夹下有toy1.md和toy2.md，生成的侧边栏是 /toy/toy1.html和 /toy/toy2.html，是我的使用方法不对吗？=。=||

**Comment by shanyuhai123** [comment]
抱歉，这是我的疏忽，因为我一般会为文件 [自定义 title](https://v1.vuepress.vuejs.org/zh/guide/frontmatter.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E5%8F%98%E9%87%8F) 来获取更好的体验，如图：
![image](https://user-images.githubusercontent.com/27122409/71715487-7b585480-2e4c-11ea-99cf-17e3af168580.png)
稍后我会更新一个版本来处理这个问题，当然你也可以像我一样添加 title 来解决。

**Comment by shanyuhai123** [comment]
> RT，请问使用插件之后生成的侧边栏为什么带.html扩展名？我的文档目录是VuePressBlog\docs\toy文件夹下有toy1.md和toy2.md，生成的侧边栏是 /toy/toy1.html和 /toy/toy2.html，是我的使用方法不对吗？=。=||

不好意思年末有点忙，看了下 vuepress 的源码，侧边栏的标题需要你自己添加上面提及的 `title`，或者使用 Markdown 语法的 `#`、`##`、 `###` 标题符号也可以。
我个人推荐使用 `title`，因为一级标题(`#`)使用时我感觉有点丑。
