### ISSUE TITLE
[Feature Request] 子文件夹嵌套支持

### ISSUE THREAD

**Issue by JasonGrass** [shanyuhai123/vuepress-plugin-auto-sidebar#20]
有个想法，现在支持子文件夹自动生成侧边栏吗？类似这样的效果：

![Snipaste_2021-03-24_08-22-04](https://user-images.githubusercontent.com/10756994/112235778-4bc48080-8c7a-11eb-8b75-2681367529a8.jpg)

我是从这里看到的：
[介绍 | vuepress-theme-reco](https://vuepress-theme-reco.recoluan.com/views/1.x/ ) 

后期会考虑添加吗

**Comment by shanyuhai123** [comment]
后续会考虑如何支持这种多层级，目前已有的解决方案是：

现在是支持子文件夹的，但是只显示同一文件夹的内容，例如我的 `os` 为上级目录，`manjaro` 为次级目录，那么侧边栏只显示次级的：
![image](https://user-images.githubusercontent.com/27122409/112244230-ed9f9980-8c89-11eb-87cb-affa220727a2.png)


如果需要对内部再划分，我目前是 `frontend` 为上级目录，`javascript` 为次级目录，内部再利用 [autoGroup](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/markdown-file-config.html#%E5%A4%9A%E4%B8%AA%E5%88%86%E7%BB%84) 二次分组：
![image](https://user-images.githubusercontent.com/27122409/112244407-3ce5ca00-8c8a-11eb-8dce-4d1ad50acdec.png)

**Comment by shanyuhai123** [comment]
主要对我来说有大量笔记要记录，而嵌套层级对内容较多时并不是很友好  :smile: ，所以早期没往这方面想。
