### ISSUE TITLE
侧边栏只显示一个文件夹层次结构

### ISSUE THREAD

**Issue by 3roman** [shanyuhai123/vuepress-plugin-auto-sidebar#24]
docs目录结构如下，但是只生成a这个目录结构，b压根不显示，不知何故？
![image](https://user-images.githubusercontent.com/14806821/118997074-f4f9cf80-b9ba-11eb-89f0-69aafed42f1b.png)

最基本的配置：
module.exports = {
  plugins: ['vuepress-plugin-auto-sidebar']
}

![image](https://user-images.githubusercontent.com/14806821/118996808-c4b23100-b9ba-11eb-821b-cd6c9582a0ba.png)

**Comment by shanyuhai123** [comment]
目前就是这样设计的，仅显示一个目录的，替代方案有 [分组选项](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/markdown-file-config.html#%E5%A4%9A%E4%B8%AA%E5%88%86%E7%BB%84)。
曾经有计划过做一个单页显示所有的计划，后来想了想，如果一页就能展示完所有文档、笔记说明数量很少，即使自己手动配置也没有什么工作量，于是就放弃了。
如果你有兴趣 PR 那再好不过了。
