### ISSUE TITLE
博主你好，依旧是我，刚刚new文章出来之后发现排序存在问题

### ISSUE THREAD

**Issue by supuwoerc** [shanyuhai123/vuepress-plugin-auto-sidebar#3]
具体就是我后创建的文件排在之前文件的上面，看了下源码没能明白你的意图，是使用的不对吗=。= 求解答=。=
```
    "vuepress-plugin-auto-sidebar": {
        titleMode: "uppercase",
        sort:'asc'
    },
```

**Comment by shanyuhai123** [comment]
你可能需要的是更准确的排序？刚刚重写了一版，示例如下：
![image](https://user-images.githubusercontent.com/27122409/72242308-0f33d880-3624-11ea-8264-30c42a6fbfa2.png)

**Comment by supuwoerc** [comment]
> 你可能需要的是更准确的排序？刚刚重写了一版，示例如下：
> ![image](https://user-images.githubusercontent.com/27122409/72242308-0f33d880-3624-11ea-8264-30c42a6fbfa2.png)

十分感谢！我自己后来写了个脚本按照创建时间在文件名前面生成时间戳强行解决了=。=

感谢您的解答~
