### ISSUE TITLE
关于排序 自定义规则，我按照文档进行了配置，可是他好像并没有生效

### ISSUE THREAD

**Issue by qianzai** [shanyuhai123/vuepress-plugin-auto-sidebar#34]
![image](https://user-images.githubusercontent.com/46664739/122143350-e56b8a80-ce83-11eb-9ae1-5fc6798c1515.png)
我试着在console打印一下，都没有出来。可能是哪里没配置好吗
![image](https://user-images.githubusercontent.com/46664739/122143500-2bc0e980-ce84-11eb-8715-ce2dc288392b.png)

**Comment by shanyuhai123** [comment]
![image](https://user-images.githubusercontent.com/27122409/122158818-d4c90d80-ce9f-11eb-9227-b08e21772059.png)

应该是没什么问题，要不然确认下版本是否为 `2.2.3` ？

**Comment by shanyuhai123** [comment]
感觉自定义不是很实用，这两天应该会更新下最简单的数字排序的功能（我也不知道为啥之前没做这个，反而做了[精准排序](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/markdown-file-config.html#autoprev-autonext) 这种复杂行为的）。

**Comment by qianzai** [comment]
> ![image](https://user-images.githubusercontent.com/27122409/122158818-d4c90d80-ce9f-11eb-9227-b08e21772059.png)
> 
> 应该是没什么问题，要不然确认下版本是否为 `2.2.3` ？

解决了，开无痕就好了，奇奇怪怪🙃

**Comment by shanyuhai123** [comment]
已新增更友好简单的[数值排序](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/markdown-file-config.html#autosort)，可以更新到 v2.3.0 尝试一下 :smiley:
