### ISSUE TITLE
能否根据侧边栏路径信息，生成一个可以跳转的md文件

### ISSUE THREAD

**Issue by qianzai** [shanyuhai123/vuepress-plugin-auto-sidebar#37]
加入文档都在docs目录里面，目录结构如下

```
docs/
├── README.md
├── T1
│   ├── README.md
│   └── t1.md
└── T2
    ├── README.md
    └── t2.md
```

想做一个全部的大纲，能否生成一个如下的md文件呢。

- [docs](/)
  - [T1](/docs/)
    - [t1](docs/t1)
  - [T2](/docs/)
    - [t2](/docs/t2)

```markdown
- [docs](/)
  - [T1](/docs/)
    - [t1](docs/t1)
  - [T2](/docs/)
    - [t2](/docs/t2)
```

路径文件夹里面具体的顺序按照 **插件** 生成侧边栏的顺序。

**Comment by qianzai** [comment]
哈哈哈，不怎么会这些，正在学。🐶保命~

**Comment by shanyuhai123** [comment]
也可以，后面我考虑下扩展 cli 功能。

**Comment by shanyuhai123** [comment]
在这个基础上 `sitemap` 的功能写了一半最后还是删了，感觉需要克制功能 😿
如果这个插件的名字是 `vuepress-plugin-route` 倒还可以杂糅进来，所以该 issue 关闭了。
