### ISSUE TITLE
Sidebar groups

### ISSUE THREAD

**Issue by Doc1993** [shanyuhai123/vuepress-plugin-auto-sidebar#38]
Is there a way to auto create sidebar **groups** ?

**Comment by shanyuhai123** [comment]
Now, it only supports [configuration](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/markdown-file-config.html#more-groups) within markdown files.
I've considered adding regular matching, but it would be more complicated and less friendly, do you have some suggestions?

**Comment by Doc1993** [comment]
Interesting. I think your solution is good enough. Currently just starting to look around how vuepress functions and found sidebars to be really troublesome. I have used docusaurus before where sidebars are autogenerated.
