### ISSUE TITLE
生成的侧边栏目录是带路径，请问还有哪些地方需要设置的

### ISSUE THREAD

**Issue by y-jm** [shanyuhai123/vuepress-plugin-auto-sidebar#39]
我想生成是根据markdown一级标题生成侧边栏目录结构，现在是/test/t.html，是不是还有哪些地方需要设置的

**Comment by shanyuhai123** [comment]
应该与 #2 是一样的问题，需要设置标题

**Comment by y-jm** [comment]
> 应该与 #2 是一样的问题，需要设置标题

---
title: 标题
---
是这样吗，我设置过，没有用

**Comment by shanyuhai123** [comment]
可以发个 markdown 截图看下，或者尝试下 #、##、 ### 符号

**Comment by y-jm** [comment]
> 可以发个 markdown 截图看下，或者尝试下 #、##、 ### 符号
🤦‍♂️是我自己的问题，我在vscode编辑，插件自动在头部添加东西，去掉就没事了
