### ISSUE TITLE
文档名字为中文的如何解决编码问题

### ISSUE THREAD

**Issue by mfkdgefhn** [shanyuhai123/vuepress-plugin-auto-sidebar#40]
如果我的MD文件是以中文命名的，需要怎么编码，VUE才不会提示
`vue-router.esm.js?8c4f:16 [vue-router] Route with path "/docu/portal/Portal操作手册.html" contains unencoded characters, make sure your path is correctly encoded before passing it to the router. Use encodeURI to encode static segments of your path.`
![image](https://user-images.githubusercontent.com/30585888/123020188-756d7f00-d404-11eb-943e-5cd5aa2230ab.png)

**Comment by shanyuhai123** [comment]
中文文件不会出现问题，甚至你可以中文目录加 emoji：
![chinese](https://user-images.githubusercontent.com/27122409/122922587-5d5f1680-d396-11eb-807a-b507fc4f1837.png)

而且依赖这个插件的国人应该很多，如果有问题应该早就反馈了，你可以先移除这个插件排查下是否是其他插件导致的问题？

**Comment by qianzai** [comment]
> 如果我的MD文件是以中文命名的，需要怎么编码，VUE才不会提示
> `vue-router.esm.js?8c4f:16 [vue-router] Route with path "/docu/portal/Portal操作手册.html" contains unencoded characters, make sure your path is correctly encoded before passing it to the router. Use encodeURI to encode static segments of your path.`
> ![image](https://user-images.githubusercontent.com/30585888/123020188-756d7f00-d404-11eb-943e-5cd5aa2230ab.png)

有些vuepress 版本，当路径为中文时候，vue-router有问题，你也可以用下面这个插件，把中文转换成拼音
[permalink-pinyin](https://github.com/viko16/vuepress-plugin-permalink-pinyin)

**Comment by shanyuhai123** [comment]
这里应该由 [@vuepress/theme-default](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/layouts/Layout.vue#L99) 处理，我这不会进行处理。
