### ISSUE TITLE
在vuepress2.x中没法使用吗？

### ISSUE THREAD

**Issue by rockfang** [shanyuhai123/vuepress-plugin-auto-sidebar#41]
在vuepress2.x版本中，安装了插件
执行
`vuepress nav docs`
没有任何报错，也不会生成文件。
直接就执行结束了。
版本：
    "vuepress": "^2.0.0-beta.19",
    "vuepress-plugin-auto-sidebar": "^2.3.0"

**Comment by shanyuhai123** [comment]
2.x 之前未兼容，这周末看一下

**Comment by shanyuhai123** [comment]
![image](https://user-images.githubusercontent.com/27122409/124306052-789d0380-db98-11eb-832b-7636f73db70e.png)

在 v2 中 `extendsCli` 被移除所以该方式无法继续支持了。后续考虑支持 v2，但看到改动较大，所以一时也没有想好是兼容还是开新版本。
