### ISSUE TITLE
title->map配置未生效

### ISSUE THREAD

**Issue by artjourney** [shanyuhai123/vuepress-plugin-auto-sidebar#49]
使用vuepress v1版本，目录结构：
├─docs
  ├─.vuepress
  │  └─public
  │      └─java
  │          └─basic
  ├─common
  └─java
      ├─basic
      └─jvm

插件配置：
'vuepress-plugin-auto-sidebar',
    {
      title: {
        mode: "titlecase",
        map: {
          "/java/basic/": "Java基础",
          "/java/jvm/": "JVM"
        }
      }
    }

菜单显示Basic，而不是显示"Java基础"，是哪里配置有问题吗？

![e88fa743df2f98833b445b52e0ea647](https://user-images.githubusercontent.com/8003780/134809458-02fd5bbf-eedd-4d2f-8379-9baafd381e62.png)

**Comment by shanyuhai123** [comment]
你这方便更新下你的代码吗，我这本地没能复现。

**Comment by shanyuhai123** [comment]
你插件配置错了，看一下[官网](https://vuepress.vuejs.org/zh/plugin/using-a-plugin.html#%E6%8F%92%E4%BB%B6%E7%9A%84%E9%80%89%E9%A1%B9)是怎么用的：

![image](https://user-images.githubusercontent.com/27122409/134812307-57c9c795-0bf6-4c9d-8db6-440a93f43c31.png)

**Comment by artjourney** [comment]
果然是我插件都配置错了，其他插件也配置错了，现在问题解决了，太感谢您了！
