### ISSUE TITLE
[Feature request] 自定义排序规则

### ISSUE THREAD

**Issue by realDuang** [shanyuhai123/vuepress-plugin-auto-sidebar#5]
配置项里能否导出一个函数接口作为传入给sort()的排序规则呢？

like：
```js
{
  ...
  sortRules: function(a,b) {
    return a.split('/')[0].parseInt() - b.split('/')[0].parseInt()
  }
}
```

使用ASCII方式排序毕竟是对有自动排序需求的人来说有些鸡肋了

**Comment by shanyuhai123** [comment]
好的，感谢您的意见，大概晚上更新一下。

**Comment by realDuang** [comment]
感谢更新，但是功能实现有些问题，我看了下代码，下面这一段mode为function与字符串的情况不是等价的。

```js
const titleSort = (obj, mode, key = "filename") => Object.values(obj).forEach(s => {
  if (typeof mode === "function") {
    return s.sort(mode);
  }

  s.sort((SORT_OPTIONS[mode] || SORT_OPTIONS["asc"])(key))
});
```

应该是：
```js
  if (typeof mode === "function") {
    return s.sort(mode(key));
  }
```
以解构高阶。

BTW，如果必须要实现高阶的目的是为了指定一个key值的话，那为什么不把key导出来呢？

**Comment by shanyuhai123** [comment]
你是对的，我搞错了。
导出 key 暂时没有好的思路。

**Comment by shanyuhai123** [comment]
你 closed 的 pr 我可以 reopen 吗

**Comment by realDuang** [comment]
> 你 closed 的 pr 我可以 reopen 吗

嗯嗯可以的。

**Comment by realDuang** [comment]
关于导出key，我的想法是，将导出的排序规则对象化。利用重载判断sort还是挺难维护的。

大概长成这样

```ts
interface sortOptions {
   sortMode: 'asc' || 'desc' || 'custom',
   sortFn?: Function,
   sortKey: String
 }
```

但这可能包含一个breaking change，所以需要你取舍一下啦

**Comment by hzmming** [comment]
请问可以按时间排序么？谢谢

**Comment by shanyuhai123** [comment]
> 请问可以按时间排序么？谢谢

已支持，可以指定 sort 的 mode 为 [created_time_asc 或 created_time_desc](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/plugin-options.html#_1-%E5%86%85%E7%BD%AE%E7%9A%84%E8%A7%84%E5%88%99)。
