### ISSUE TITLE
关于侧边栏及自动侧边栏问题？

### ISSUE THREAD

**Issue by qilane** [shanyuhai123/vuepress-plugin-auto-sidebar#51]
问题1：
老铁能否参考下面这个插件做一个自动侧边栏功能吗？不然每次新建文章，都要去sidebar中添加一下！

问题2：
貌似侧边栏文件及文件夹不识别汉字，只能英文或数字，这就导致文档很多的情况下不是很方便，希望老铁能优化一下，哈哈！

**Comment by qilane** [comment]
好像搞错地方了！！！

**Comment by shanyuhai123** [comment]
问题 1 ，这插件就是用来生成侧边栏的。
问题 2 的[汉字甚至 emoji ](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar/tree/master/packages/vuepress-docs-gh-pages/docs/zh)都可以：
![image](https://user-images.githubusercontent.com/27122409/144696214-523b914f-b4f1-4721-9a55-b898c25878c4.png)
