### ISSUE TITLE
如何把当前目录的文件，以及子目录都显示在sidebar呢？

### ISSUE THREAD

**Issue by scil** [shanyuhai123/vuepress-plugin-auto-sidebar#61]
譬如
```
.
..
dir1/
dir2/
README.md
```

可以把 dir1 和 dir2 及其内容也显示出来？

**Comment by shanyuhai123** [comment]
分组仅可以这样 https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/markdown-file-config.html#%E5%A4%9A%E4%B8%AA%E5%88%86%E7%BB%84

**Comment by scil** [comment]
谢谢。

目前感觉主题 vuepress-theme-hope 的 [sidebar](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E9%93%BE%E6%8E%A5) 挺强大吧。

**Comment by shanyuhai123** [comment]
> 谢谢。
> 
> 目前感觉主题 vuepress-theme-hope 的 [sidebar](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E9%93%BE%E6%8E%A5) 挺强大吧。

看了下，应该是需要手动追加，如果你使用该主题可以直接用它那个

**Comment by scil** [comment]
> > 谢谢。
> > 目前感觉主题 vuepress-theme-hope 的 [sidebar](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E9%93%BE%E6%8E%A5) 挺强大吧。
> 
> 看了下，应该是需要手动追加，如果你使用该主题可以直接用它那个

我现在只能手动了。搜到这片文章 [vuePress侧边栏sidebar分组自动生成的实现](https://blog.csdn.net/weixin_42068913/article/details/116207129) 好像能自动处理多级子目录，先放到这，方便后来者。
