### ISSUE TITLE
默认分组

### ISSUE THREAD

**Issue by countryMan1993** [shanyuhai123/vuepress-plugin-auto-sidebar#65]
一个文件夹内的默认的分组名称如何去除，想全部都自定义分组，不然就得改文件夹名称

**Comment by shanyuhai123** [comment]
临时解决方案为将其中一个分组用[标题的映射](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/plugin-options.html#_2-%E6%98%A0%E5%B0%84)

**Comment by shanyuhai123** [comment]
更新到 `npm i vuepress-plugin-auto-sidebar@2.4.0-alpha.5`，以增加该[配置项](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/zh/features/plugin-options.html#removeemptygroup-%E9%9A%90%E8%97%8F%E7%A9%BA%E5%88%86%E7%BB%84)：

```js
module.exports = {
  plugins: [
    "vuepress-plugin-auto-sidebar": {
      removeEmptyGroup: true
    }
  ]
}
```
