### ISSUE TITLE
打包后部署到nginx，侧边栏就没了，开发环境正常

### ISSUE THREAD

**Issue by aoxiangsky** [shanyuhai123/vuepress-plugin-auto-sidebar#68]
打包后部署到nginx，侧边栏就没了，开发环境正常

**Comment by aoxiangsky** [comment]
version: 2.3.2

**Comment by aoxiangsky** [comment]
windows 上打包是正常的，centos7上打包不对

**Comment by aoxiangsky** [comment]
看是不是路径分隔符的问题，window上和linux上不一样的，一个是 \ ，一个是 / ，用 path.sep 来替代

**Comment by shanyuhai123** [comment]
好的，谢谢反馈。

不过我的开发及 github action 均为 linux 环境，我稍后会排查一下问题。

**Comment by shanyuhai123** [comment]
还有一个可能是你的 CentOS 中 Nginx 找不到中文路径引起的，你可以看下是否是该问题。
