### ISSUE TITLE
如何隐藏文件夹的名字

### ISSUE THREAD

**Issue by qtanran** [shanyuhai123/vuepress-plugin-auto-sidebar#69]
![image](https://user-images.githubusercontent.com/48440870/164135662-163f8110-9054-4ad4-b9b3-e3229176c87a.png)
![image](https://user-images.githubusercontent.com/48440870/164135735-d6f7bd55-82dc-418f-a065-cc8d1a05fa83.png)
请问大佬可以在侧边栏中把这个文件夹的名字隐藏掉吗？

**Comment by shanyuhai123** [comment]
这个做不到，这个插件目标是收集归档大量相同的内容，你可以用原生，或者找个其他主题带 tag 的。
