### ISSUE TITLE
安装后，无法启动项目了

### ISSUE THREAD

**Issue by mantoudahanv** [shanyuhai123/vuepress-plugin-auto-sidebar#7]
安装后，无法启动项目了，请问咋整

**Comment by shanyuhai123** [comment]
请问您配置了什么，无法启动的报错信息是什么？
方便的话可以上传一下您的项目吗？

**Comment by mantoudahanv** [comment]
我就是个萌新，我github上vue项目就是跟着你的视频学的，我刚上传点击deploy.sh后，，但是github里面没有刷新
shanyuhai123 <notifications@github.com> 于2020年3月16日周一 下午6:39写道：

**Comment by shanyuhai123** [comment]
那你确认是原先可以启动，安装后反而启动不了了么？
不需要使用 `deploy.sh` ，直接 git push 就可以了。

**Comment by mantoudahanv** [comment]
我好像上传到我vue/master分支里了，您有时间帮我看下么。我在没安装前，是vuepress的自动生成侧边栏根据我的md文章中N个标题才生成3个侧边栏。我以为他的有问题然后再安装的你这边的，安装后在终端运行npm
run docs:dev，一秒就结束了。8080也是打不开

shanyuhai123 <notifications@github.com> 于2020年3月16日周一 下午7:05写道：

**Comment by shanyuhai123** [comment]
那个我应该不是你项目中那么使用的。
应该在 plugins 中启用，你可以看下[使用说明](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar#1-%E6%97%A0%E6%B3%A8%E9%87%8A)。
