### ISSUE TITLE
Sidebar not being generated

### ISSUE THREAD

**Issue by FaresKi** [shanyuhai123/vuepress-plugin-auto-sidebar#74]
Hey!
First of all, thanks for the plugin.
I seem to have an issue understanding how to use the plugin, because I haven't managed to implement it correctly:
Here is my config:
```js
// 
module.exports = {
  plugins: [
    'vuepress-plugin-auto-sidebar',
    {
      titleMap: {
        'core-concepts': 'Core Concepts',
        presentation: 'Presentation'
      },
    },
  ],
};
```
here is my project structure:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/46092308/179608040-d0100971-66ba-49d7-8f28-2871dd779f85.png">

and this is the console log with these error messages:
```
> vuepress dev docs

warning an anonymous plugin or theme was detected and ignored
warning an anonymous plugin or theme was detected and ignored
info Initializing VuePress and preparing data...

  vite v2.9.14 dev server running at:
```
This is the what's rendered:
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/46092308/179607670-f048137d-4012-4841-9e7f-8e4ae911a5f3.png">

Do you have an idea of what might be missing?
Thanks in advance,
Fares

**Comment by shanyuhai123** [comment]
your config format is incorrect, you can visit [vuepress docs](https://vuepress.vuejs.org/plugin/using-a-plugin.html#plugin-options) see more, and now `titleMap` was [changed](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/features/plugin-options.html#_2-path-map), 

```js
module.exports = {
  plugins: [
    ["vuepress-plugin-auto-sidebar", {
      title: {
       map: {
         '/introduction/core-concepts': 'Core Concepts',
         '/introduction/presentation': 'Presentation'
       }
      }
    }],
   // you can add other plugins below
  ]
}
```

**Comment by FaresKi** [comment]
Thanks!
