### ISSUE TITLE
没有生成.vuepress/nav.js 

### ISSUE THREAD

**Issue by tofulife** [shanyuhai123/vuepress-plugin-auto-sidebar#8]
第一次运行`npm run docs:dev` 没有生成`.vuepress/nav.js` ，是什么情况

**Comment by shanyuhai123** [comment]
你首先需要在插件中启用它：
```js
module.exports = {
  plugins: [
    "vuepress-plugin-auto-sidebar": {
    	nav: true
    }
  ],
}
```
第一次执行 `npm run docs:dev` 后看到生成了该文件后，再[引入](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar#4-nav)它。
