### ISSUE TITLE
配置插件但是无法生效

### ISSUE THREAD

**Issue by kemaosen** [shanyuhai123/vuepress-plugin-auto-sidebar#9]
docs目录下有个a文件夹 
a文件夹下有A.md B.md README.md
启动项目 只能到README.md中 侧边栏没有目录 但是访问可以访问到A.md B.md
我是哪里做错了什么么？

**Comment by shanyuhai123** [comment]
有配置的截图或者项目地址看一下吗？

**Comment by kemaosen** [comment]
十分感谢你的回信 我通过别的方式配置了动态路由了。
但是比较麻烦 对于你的插件还是很感兴趣，但是我找不到该如何配置，
我重新修改了下          https://gitee.com/kms-123/demo.git
这是项目地址 
在2020年4月12日 13:04，shanyuhai123<notifications@github.com> 写道：

有配置的截图或者项目地址看一下吗？

**Comment by shanyuhai123** [comment]
因为你把 `plugins` 放到 `themeConfig` 中了，应当与 `themeConfig` 同级。

**Comment by shanyuhai123** [comment]
我觉得我应该给 plugins 位置加个提示了，跟你有同样问题的遇到四五个了。

**Comment by kemaosen** [comment]
我按你说的更改了 确实可以使用，还是粗心了
如果我想设置三级目录支持么？




在2020年4月12日 13:43，shanyuhai123<notifications@github.com> 写道：

因为你把 plugins 放到 themeConfig 中了，应当与 themeConfig 同级。

**Comment by shanyuhai123** [comment]
对目录层级是没有限制的，其实它只是一个对同一目录下所有文章进行[分组的一个插件](https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/questions.html#_1-%E5%AE%83%E7%9A%84%E4%BD%9C%E7%94%A8%E6%98%AF%E7%94%9F%E6%88%90%E4%BE%A7%E8%BE%B9%E6%A0%8F%E5%90%97%EF%BC%9F)。

**Comment by kemaosen** [comment]
可以在详细说下么 我在目录下面又添加了一个目录 但是他并没有显示在页面上（侧边栏）
我在浏览器url上输入目录名称是可以访问的 
在2020年4月12日 14:01，shanyuhai123<notifications@github.com> 写道：

对目录层级是没有限制的，其实它只是一个对同一目录下所有文章进行分组的一个插件。

**Comment by shanyuhai123** [comment]
比如你的目录为 a 下面是 b 再下面是 c，那你访问路径 a/b 就是 b 目录下面的文件（不包含 c 下面的），你访问路径 a/b/c 才能看到 c 下面的，至于你希望访问 a/b 时能看到 c 的内容这个功能正在考虑实现中…


 
---原始邮件---
发件人: "kemaosen"<notifications@github.com&gt;
发送时间: 2020年4月12日 14:11:17
收件人: "shanyuhai123/vuepress-plugin-auto-sidebar"<vuepress-plugin-auto-sidebar@noreply.github.com&gt;;
抄送: "shanyuhai123"<864299347@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [shanyuhai123/vuepress-plugin-auto-sidebar] 配置插件但是无法生效 (#9)




 
 
 可以在详细说下么 我在目录下面又添加了一个目录 但是他并没有显示在页面上（侧边栏）
 我在浏览器url上输入目录名称是可以访问的 
 在2020年4月12日 14:01，shanyuhai123<notifications@github.com&gt; 写道：
 
 对目录层级是没有限制的，其实它只是一个对同一目录下所有文章进行分组的一个插件。

**Comment by kemaosen** [comment]
好的 谢谢你的解答 目前我已经找到一种别的实现方法，调试花了我很长时间
你的插件十分的好用


在2020年4月12日 14:18，shanyuhai123<notifications@github.com> 写道：

比如你的目录为 a 下面是 b 再下面是 c，那你访问路径 a/b 就是 b 目录下面的文件（不包含 c 下面的），你访问路径 a/b/c 才能看到 c 下面的，至于你希望访问 a/b 时能看到 c 的内容这个功能正在考虑实现中…



---原始邮件---
发件人: "kemaosen"<notifications@github.com&gt;
发送时间: 2020年4月12日 14:11:17
收件人: "shanyuhai123/vuepress-plugin-auto-sidebar"<vuepress-plugin-auto-sidebar@noreply.github.com&gt;;
抄送: "shanyuhai123"<864299347@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [shanyuhai123/vuepress-plugin-auto-sidebar] 配置插件但是无法生效 (#9)






可以在详细说下么 我在目录下面又添加了一个目录 但是他并没有显示在页面上（侧边栏）
我在浏览器url上输入目录名称是可以访问的
在2020年4月12日 14:01，shanyuhai123<notifications@github.com&gt; 写道：

对目录层级是没有限制的，其实它只是一个对同一目录下所有文章进行分组的一个插件。
